# Generated by Django 6.0.4 on 2026-05-02 01:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_rewrite_transaction'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='finance_tra_buy_ord_4f39a9_idx',
            old_name='finance_tra_buy_ord_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='finance_tra_token_d1b1c0_idx',
            old_name='finance_tra_token_idx',
        ),
        migrations.AddField(
            model_name='transaction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Timestamp del borrado lógico. NULL = registro activo.', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='False indica un registro borrado lógicamente (soft delete).'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación. Inmutable post-creación.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal. Ver documentación de diseño para justificación.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación. Gestionado automáticamente.'),
        ),
    ]
