# Generated by Django 6.0.4 on 2026-04-21 20:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal. Ver documentación de diseño para justificación.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación. Inmutable post-creación.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación. Gestionado automáticamente.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False indica un registro borrado lógicamente (soft delete).')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Timestamp del borrado lógico. NULL = registro activo.', null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('synopsis', models.TextField(blank=True, default='')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal. Ver documentación de diseño para justificación.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación. Inmutable post-creación.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación. Gestionado automáticamente.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False indica un registro borrado lógicamente (soft delete).')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Timestamp del borrado lógico. NULL = registro activo.', null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('bio', models.TextField(blank=True, default='')),
                ('nationality', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'indexes': [models.Index(fields=['slug'], name='catalog_aut_slug_c3c553_idx')],
            },
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal. Ver documentación de diseño para justificación.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación. Inmutable post-creación.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación. Gestionado automáticamente.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False indica un registro borrado lógicamente (soft delete).')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Timestamp del borrado lógico. NULL = registro activo.', null=True)),
                ('role', models.CharField(choices=[('primary', 'Primary Author'), ('translator', 'Translator'), ('editor', 'Editor')], default='primary', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_books', to='catalog.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_authors', to='catalog.book')),
            ],
            options={
                'unique_together': {('book', 'author', 'role')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', through='catalog.BookAuthor', to='catalog.author'),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal. Ver documentación de diseño para justificación.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación. Inmutable post-creación.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación. Gestionado automáticamente.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False indica un registro borrado lógicamente (soft delete).')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Timestamp del borrado lógico. NULL = registro activo.', null=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'indexes': [models.Index(fields=['slug'], name='catalog_gen_slug_b52fa1_idx')],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='books', to='catalog.genre'),
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal. Ver documentación de diseño para justificación.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación. Inmutable post-creación.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación. Gestionado automáticamente.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False indica un registro borrado lógicamente (soft delete).')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Timestamp del borrado lógico. NULL = registro activo.', null=True)),
                ('language', models.CharField(default='es', max_length=10)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('format', models.CharField(choices=[('epub', 'EPUB'), ('pdf', 'PDF'), ('audio', 'Audiobook')], default='epub', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('file', models.FileField(help_text='Archivo del libro. Almacenado en directorio protegido. Nunca servir directamente desde MEDIA_URL; usar la view de descarga autenticada en library/views.py.', upload_to='protected/book_files/')),
                ('published_date', models.DateField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, default='', max_length=255)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='catalog.book')),
            ],
            options={
                'verbose_name': 'Edition',
                'verbose_name_plural': 'Editions',
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_gte_0', violation_error_message='El precio no puede ser negativo.')],
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['slug'], name='catalog_boo_slug_7fab6a_idx'),
        ),
    ]
