# Generated by Django 6.0.4 on 2026-04-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Marcar como True para destacar este libro en la Landing Page.'),
        ),
    ]
