# Generated by Django 6.0.4 on 2026-04-29 20:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_book_difficulty_level_book_is_published_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterAudio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal. Ver documentación de diseño para justificación.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación. Inmutable post-creación.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación. Gestionado automáticamente.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False indica un registro borrado lógicamente (soft delete).')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Timestamp del borrado lógico. NULL = registro activo.', null=True)),
                ('voice_name', models.CharField(help_text="Ej: 'Carito - Colombiana'", max_length=100)),
                ('audio_file', models.FileField(upload_to='protected/chapter_audios/')),
                ('sync_file', models.FileField(blank=True, help_text='Sube un archivo JSON de alineación. El sistema lo leerá y guardará en alignment_data automáticamente.', null=True, upload_to='temp_sync/')),
                ('alignment_data', models.JSONField(blank=True, help_text='Datos de alineación extraídos del JSON.', null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='catalog.chapter')),
            ],
            options={
                'verbose_name': 'Chapter Audio',
                'verbose_name_plural': 'Chapter Audios',
                'ordering': ['chapter', 'voice_name'],
            },
        ),
    ]
