# Generated by Django 6.0.4 on 2026-05-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_chapteraudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='copyright_notice',
            field=models.TextField(blank=True, default='Este libro electrónico está libre de restricciones de derechos de autor en Chile (según la Ley N° 17.336 de Propiedad Intelectual). Si no se encuentra en Chile, debe consultar las leyes locales para verificar que el contenido de este libro electrónico esté libre de restricciones en su país de residencia. Literatus Novelist promueve el acceso a la cultura respetando siempre los derechos vigentes.', help_text='Aviso legal sobre derechos de autor y dominio público.'),
        ),
    ]
