# Generated by Django 6.0.4 on 2026-05-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_book_copyright_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Versión PDF de la obra para descarga directa de usuarios que la posean.', null=True, upload_to='protected/pdf_downloads/'),
        ),
    ]
