# Generated by Django 6.0.4 on 2026-05-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_book_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='download_count',
            field=models.PositiveIntegerField(default=0, help_text='Número total de descargas de la obra.'),
        ),
        migrations.AddField(
            model_name='book',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Número total de visualizaciones de la ficha del libro.'),
        ),
    ]
