# Generated by Django 6.0.4 on 2026-05-01 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_book_download_count_book_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='authors/photos/'),
        ),
        migrations.AddField(
            model_name='author',
            name='recommended_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_for_author', to='catalog.book'),
        ),
        migrations.AddField(
            model_name='author',
            name='themes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
