# Generated by Django 6.0.4 on 2026-05-03 00:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_author_photo_author_recommended_book_author_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='mood',
            field=models.CharField(blank=True, choices=[('Feliz', 'Feliz'), ('Triste', 'Triste'), ('Misterioso', 'Misterioso'), ('Tenso', 'Tenso'), ('Romántico', 'Romántico'), ('Épico', 'Épico'), ('Melancólico', 'Melancólico'), ('Inspirador', 'Inspirador'), ('Filosófico', 'Filosófico'), ('Oscuro', 'Oscuro'), ('Aventurero', 'Aventurero')], help_text='Estado de ánimo general de la obra para el recomendador.', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal. Ver documentación de diseño para justificación.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación. Inmutable post-creación.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación. Gestionado automáticamente.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False indica un registro borrado lógicamente (soft delete).')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Timestamp del borrado lógico. NULL = registro activo.', null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'indexes': [models.Index(fields=['slug'], name='catalog_tag_slug_676fab_idx')],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='books', to='catalog.tag'),
        ),
    ]
