# Generated by Django 6.0.4 on 2026-05-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_book_mood_tag_book_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='gutenberg_id',
            field=models.IntegerField(blank=True, help_text='ID numérico del libro en Project Gutenberg. Usado para sincronización y deduplicación.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='text_file_path',
            field=models.CharField(blank=True, default='', help_text='Ruta relativa dentro de MEDIA_ROOT al archivo de texto completo guardado en el servidor (gutenberg_texts/{id}/full_text.txt).', max_length=512),
        ),
    ]
