# Generated by Django 6.0.4 on 2026-05-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_tag_name_alter_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='death_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='wikipedia_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('archived', 'Archivado')], default='draft', help_text='Estado de la obra en el flujo de trabajo.', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='mood',
            field=models.CharField(blank=True, choices=[('Feliz', 'Feliz'), ('Triste', 'Triste'), ('Misterioso', 'Misterioso'), ('Tenso', 'Tenso'), ('Romántico', 'Romántico'), ('Épico', 'Épico'), ('Melancólico', 'Melancólico'), ('Inspirador', 'Inspirador'), ('Filosófico', 'Filosófico'), ('Oscuro', 'Oscuro'), ('Aventurero', 'Aventurero')], help_text='Estado de ánimo general de la obra para el recomendador.', max_length=150, null=True),
        ),
    ]
