# Generated by Django 6.0.4 on 2026-05-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_author_birth_year_author_death_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='edition',
            name='file',
            field=models.FileField(help_text='Archivo del libro. Almacenado en directorio protegido. Nunca servir directamente desde MEDIA_URL; usar la view de descarga autenticada en library/views.py.', max_length=512, upload_to='protected/book_files/'),
        ),
    ]
