# Generated by Django 6.0.4 on 2026-05-22 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_book_slug_alter_edition_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='gutenberg_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='text_file_path',
        ),
    ]
