# Generated by Django 6.0.4 on 2026-05-22 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_remove_book_gutenberg_id_remove_book_text_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='mood',
        ),
    ]
