# Generated by Django 6.0.4 on 2026-06-01 02:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_remove_book_mood'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_review_per_book',
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('book', 'order'), name='unique_chapter_order', violation_error_message='Este libro ya tiene un capítulo con ese número de orden.'),
        ),
        migrations.AddConstraint(
            model_name='chapteraudio',
            constraint=models.UniqueConstraint(fields=('chapter', 'voice_name'), name='unique_chapter_audio_voice', violation_error_message='Ya existe un audio con esa voz para este capítulo.'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'book'), name='unique_active_review_per_book', violation_error_message='El usuario ya ha reseñado activamente este libro.'),
        ),
    ]
