# Generated by Django 6.0.4 on 2026-06-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_db_audit_unique_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to='book_covers/'),
        ),
    ]
