# Generated by Django 6.0.4 on 2026-06-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to='authors/photos/'),
        ),
    ]
