# Generated by Django 6.0.4 on 2026-06-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_author_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_covers/'),
        ),
    ]
