# Generated by Django 6.0.4 on 2026-06-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_genre_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='category_covers/'),
        ),
    ]
