# Generated by Django 6.0.4 on 2026-04-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ink_balance',
            field=models.PositiveIntegerField(default=50, help_text='Tokens de energía (Tinta) disponibles para chatear con personajes de IA.'),
        ),
    ]
