# Generated by Django 6.0.4 on 2026-06-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_phase5_chat_unlock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_color',
            field=models.CharField(default='#3b82f6', max_length=20),
        ),
    ]
