# Generated by Django 6.0.4 on 2026-06-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_avatar_profile_avatar_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(default='default', help_text='Tema visual preferido del usuario.', max_length=50),
        ),
    ]
