# Generated by Django 6.0.4 on 2026-04-21 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_engine.chatsession'),
        ),
        migrations.AddConstraint(
            model_name='aiavatar',
            constraint=models.CheckConstraint(condition=models.Q(('temperature__gte', 0.0), ('temperature__lte', 1.0)), name='valid_temperature', violation_error_message='La temperatura debe estar entre 0.0 y 1.0.'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', 'created_at'], name='ai_engine_c_user_id_4cd316_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='ai_engine_c_session_b8fb58_idx'),
        ),
    ]
