# Generated by Django 6.0.4 on 2026-04-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiavatar',
            name='behavioral_context',
            field=models.TextField(blank=True, help_text='Motivaciones secretas, situación emocional actual de este personaje.'),
        ),
        migrations.AddField(
            model_name='aiavatar',
            name='greeting_message',
            field=models.TextField(default='Hola, viajero.', help_text='Mensaje introductorio fijo que arranca la sesión. Actúa como ancla.'),
        ),
        migrations.AddField(
            model_name='aiavatar',
            name='sample_dialogues',
            field=models.TextField(blank=True, help_text='Bloques literales de la obra (o inventados) que le dicen a la IA cómo contestar.'),
        ),
    ]
