# Generated by Django 6.0.4 on 2026-04-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0003_aiavatar_behavioral_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiavatar',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Descripción breve del personaje para mostrar en su ficha de perfil.'),
        ),
        migrations.AddField(
            model_name='aiavatar',
            name='is_major_character',
            field=models.BooleanField(default=True, help_text='Si es un personaje principal, aparece destacado en el panel.'),
        ),
        migrations.AddField(
            model_name='aiavatar',
            name='unlock_at_chapter',
            field=models.PositiveIntegerField(default=0, help_text='Capítulo (base 0) a partir del cual el usuario puede chatear con este personaje.'),
        ),
        migrations.AlterField(
            model_name='aiavatar',
            name='greeting_message',
            field=models.TextField(default='Hola, viajero.', help_text='Mensaje introductorio fijo que arranca la sesión.'),
        ),
        migrations.AlterField(
            model_name='aiavatar',
            name='sample_dialogues',
            field=models.TextField(blank=True, help_text='Bloques literales de la obra para guiar el estilo de respuesta.'),
        ),
    ]
