# Generated by Django 6.0.4 on 2026-04-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0004_phase5_chat_unlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiavatar',
            name='is_author',
            field=models.BooleanField(default=False, help_text='Si True, este avatar representa al autor de la obra y aparece en sección propia.'),
        ),
        migrations.AlterField(
            model_name='aiavatar',
            name='model_name',
            field=models.CharField(default='gemini-2.5-flash', help_text="Identificador del modelo LLM (e.g. 'gemini-2.5-flash', 'gpt-4o').", max_length=50),
        ),
    ]
