# Generated by Django 6.0.4 on 2026-05-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0005_add_is_author_to_aiavatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiavatar',
            name='model_name',
            field=models.CharField(default='gemini-2.5-flash', help_text="Identificador del modelo LLM (e.g. 'gemini-2.5-flash', 'gpt-4o').", max_length=100),
        ),
    ]
