# Generated by Django 6.0.4 on 2026-05-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0006_alter_aiavatar_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiavatar',
            name='video_avatar',
            field=models.FileField(blank=True, help_text='Video en bucle para simular habla (MP4).', null=True, upload_to='ai_avatars/videos/'),
        ),
    ]
