# Generated by Django 6.0.4 on 2026-05-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0007_aiavatar_video_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiavatar',
            name='chat_count',
            field=models.PositiveIntegerField(default=0, help_text='Número total de conversaciones iniciadas con este personaje.'),
        ),
    ]
