# Generated by Django 6.0.4 on 2026-05-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0008_aiavatar_chat_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiavatar',
            name='model_name',
            field=models.CharField(default='gemini-2.0-flash', help_text="Identificador del modelo LLM (e.g. 'gemini-2.0-flash', 'gpt-4o').", max_length=255),
        ),
        migrations.AlterField(
            model_name='aiavatar',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
