# Generated by Django 6.0.4 on 2026-06-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0009_alter_aiavatar_model_name_alter_aiavatar_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiavatar',
            name='kokoro_voice_id',
            field=models.CharField(default='af_bella', help_text="ID de voz de Kokoro-82M para TTS (e.g. 'af_bella', 'af_nicole', 'em_alex', 'em_santa').", max_length=50),
        ),
    ]
