# Generated by Django 6.0.4 on 2026-06-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0010_add_kokoro_voice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiavatar',
            name='video_avatar',
        ),
        migrations.AddField(
            model_name='aiavatar',
            name='image_speaking',
            field=models.ImageField(blank=True, help_text="Imagen mostrada mientras el personaje 'habla' (ej. reproduciendo audio).", null=True, upload_to='ai_avatars/states/'),
        ),
        migrations.AddField(
            model_name='aiavatar',
            name='image_thinking',
            field=models.ImageField(blank=True, help_text='Imagen mostrada mientras la IA genera una respuesta.', null=True, upload_to='ai_avatars/states/'),
        ),
        migrations.AlterField(
            model_name='aiavatar',
            name='avatar_image',
            field=models.ImageField(blank=True, help_text='Imagen neutral/Idle del avatar mostrada en la interfaz.', null=True, upload_to='ai_avatars/'),
        ),
    ]
