# Generated by Django 6.0.4 on 2026-06-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0011_remove_aiavatar_video_avatar_aiavatar_image_speaking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiavatar',
            name='image_speaking',
        ),
        migrations.AddField(
            model_name='aiavatar',
            name='image_speaking_1',
            field=models.ImageField(blank=True, help_text='Fotograma 1 de la animación de habla (ej. boca cerrada).', null=True, upload_to='ai_avatars/states/'),
        ),
        migrations.AddField(
            model_name='aiavatar',
            name='image_speaking_2',
            field=models.ImageField(blank=True, help_text='Fotograma 2 de la animación de habla (ej. boca entreabierta).', null=True, upload_to='ai_avatars/states/'),
        ),
        migrations.AddField(
            model_name='aiavatar',
            name='image_speaking_3',
            field=models.ImageField(blank=True, help_text='Fotograma 3 de la animación de habla (ej. boca abierta).', null=True, upload_to='ai_avatars/states/'),
        ),
    ]
